// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiFcturacionTPI.Models;

public partial class Detallefactura
{
    public int Iddetalle { get; set; }

    public int Nrofactura { get; set; }

    public int Idarticulo { get; set; }

    public int Cantidad { get; set; }
    [JsonIgnore]
    public virtual Articulo IdarticuloNavigation { get; set; }
}