// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace WebApiFcturacionTPI.Models;

public partial class Factura
{
    public int Nrofactura { get; set; }

    public DateTime? Fecha { get; set; }

    public int Formapago { get; set; }

    public int Cliente { get; set; }

    
    public List<Detallefactura> Detalles { get; set; }
    public string Motivobaja { get; set; }
    [JsonIgnore]
    public virtual Cliente ClienteNavigation { get; set; }
    [JsonIgnore]
    public virtual FormasPago FormapagoNavigation { get; set; }
}