// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApiFcturacionTPI.Models;

public partial class Usuario
{
    public int Idusuario { get; set; }

    public string Usuario1 { get; set; }

    public string Contraseña { get; set; }
}